name: build(pandoc)

on:
  workflow_dispatch:
    inputs:
      version:
        default: 'latest'
        description: 'Package version'
        type: string
        required: true
  schedule:
    - cron: '0 20 * * *'

permissions:
  contents: write
  packages: write

env:
  app_name: 'pandoc'
  app_repo: 'jgm/pandoc'

jobs:
  check:
    runs-on: ubuntu-slim
    outputs:
      app_version: ${{ steps.get-version.outputs.app_version }}
      app_build: ${{ steps.check-release.outputs.app_build }}
    steps:
      - uses: actions/checkout@v6

      - name: Get Version
        id: get-version
        run: |
          if [ "${{ github.event_name }}" = "schedule" ] || [ "${{ github.event.inputs.version }}" = "latest" ]; then
            app_version=$(curl -s "https://api.github.com/repos/${{ env.app_repo }}/releases/latest" | jq -r .tag_name)
          else
            app_version=${{ github.event.inputs.version }}
          fi
          if [ -z "${app_version}" ] || [ "${app_version}" == "null" ]; then
            echo "Failed to get version"
            exit 1
          fi
          
          echo "app_version=${app_version}" >> $GITHUB_ENV
          echo "app_version=${app_version}" >> $GITHUB_OUTPUT
          echo ""
          echo "========== Build Args =========="
          echo "app_version=${app_version}"

      - name: Check Release
        id: check-release
        run: |
          gh release view ${app_version} -R ${{ github.repository }} | grep pandoc-.*-loong64.deb >/dev/null 2>&1 || echo "app_build=1" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    if: needs.check.outputs.app_build == '1'
    runs-on: ${{ matrix.runner }}
    needs: check
    env:
      app_version: ${{ needs.check.outputs.app_version }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: loong64
            platform: loongarch64
            runner: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ env.app_repo }}
          ref: ${{ env.app_version }}

      - uses: docker/setup-qemu-action@v4

      - name: Apply Patch
        run: |
          wget -qO - https://github.com/${{ github.repository }}/raw/refs/heads/main/patch_loong64.patch | git apply
          chmod +x linux/make_artifacts.sh

      - name: Build Binaries
        run: |
          DOCKER_IMAGE="ghcr.io/${{ github.repository }}:build-linux-${{ matrix.platform }}"
          DOCKER_CMD="./linux/make_artifacts.sh"
          docker run --rm \
            --platform linux/${{ matrix.arch }} \
            --env CABALOPTS="-f-export-dynamic -fembed_data_files -fhttp -fserver -flua --enable-executable-static -j4" \
            --env GHCOPTS="-j4 +RTS -A256m -RTS -split-sections -optc-Os -optl=-pthread -optc-mcmodel=medium" \
            --volume $(pwd):/io/${{ env.app_name }} \
            --workdir /io/${{ env.app_name }} \
            ${DOCKER_IMAGE} \
            sh -c "${DOCKER_CMD}"

      - name: Check Binaries
        run: |
          mv linux-${{ matrix.arch }} dist
          ls -al dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.app_name }}-binaries
          path: dist

  release:
    if: needs.check.outputs.app_build == '1'
    runs-on: ubuntu-latest
    needs:
      - check
      - build
    env:
      app_version: ${{ needs.check.outputs.app_version }}
    steps:
      - uses: actions/checkout@v6

      - name: Download release
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ env.app_name }}-*
          path: dist
          merge-multiple: true

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${{ env.app_version }}"
          gh release create "${TAG_NAME}" \
            --generate-notes \
            --title "${TAG_NAME}" \
            dist/*